#version: '3.1'
version: '3.1'

services:
  mp:
    depends_on:
      - mp-db
    build:
      context: .
    restart: always

  mp-db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: 'mp_db'
      MYSQL_USER: 'mp_db_user'
      MYSQL_PASSWORD: 'mp_db_user'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3307:3306'
    expose:
      - '3307'